# Generated by Django 4.2.1 on 2023-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.IntegerField(blank=True)),
                ('anwser', models.CharField(blank=True, max_length=40)),
                ('token', models.CharField(default=None, max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=40)),
                ('similarity', models.IntegerField()),
                ('anwser', models.CharField(max_length=40)),
                ('game_num', models.IntegerField()),
            ],
        ),
    ]
